// WHAT EACH CATEGORY IS, AND WHAT IT TAKES TO FILL IT.
//
// The bands answer 'what does this cost'. On their own they do not answer 'what am I buying
// at that rate', which is the question a subcontractor pricing a bid actually has.
//
// THESE ARE FARAUDIT EDITORIAL SUMMARIES, and the panel says so where it prints them. They are
// not a government standard and not an SCA Directory of Occupations entry — a definition is not
// a claim about what the Government has determined, and it must not be dressed as one.
export const CATEGORY_SPEC: Record<string, { what: string; quals: string }> = {
  "Mechanical Engineer I": { what: "Designs and analyses mechanical parts and assemblies to a customer drawing or performance spec, under supervision.", quals: "BS mechanical engineering, 0–3 yrs. CAD proficiency. No clearance typical." },
  "Mechanical Engineer II": { what: "Owns component design through qualification, including tolerance stacks, materials selection and test support.", quals: "BS + 3–8 yrs. GD&T. Secret clearance common on DoD programs." },
  "Mechanical Engineer III": { what: "Leads the mechanical design of a subsystem and signs off analysis other engineers depend on.", quals: "BS/MS + 8+ yrs. Often a technical lead. Secret or higher." },
  "Systems Engineer I": { what: "Traces requirements between the customer spec and the design, and maintains the verification matrix.", quals: "BS engineering, 0–3 yrs. Requirements tooling (DOORS/Jama)." },
  "Systems Engineer II": { what: "Owns requirements decomposition and interface definition across subsystems.", quals: "BS + 3–8 yrs. INCOSE ASEP/CSEP common. Secret typical." },
  "Systems Engineer III": { what: "Sets the technical baseline for a program and chairs interface and change control.", quals: "BS/MS + 8+ yrs. CSEP. Secret or TS depending on program." },
  "Software Engineer I": { what: "Implements and tests software to an existing architecture and coding standard.", quals: "BS CS/CE, 0–3 yrs. One compiled language plus scripting." },
  "Software Engineer II": { what: "Owns a module end to end including design, test and integration onto target hardware.", quals: "BS + 3–8 yrs. Embedded or mission software. Secret common." },
  "Software Engineer III": { what: "Sets software architecture for a subsystem and owns build, integration and release.", quals: "BS/MS + 8+ yrs. Often DO-178 or safety-critical background." },
  "Electrical Engineer I": { what: "Designs circuits and supports board bring-up under direction.", quals: "BS EE, 0–3 yrs. Schematic capture and lab instrumentation." },
  "Electrical Engineer II": { what: "Owns board-level design through qualification including EMI/EMC and environmental test.", quals: "BS + 3–8 yrs. MIL-STD-461/810 exposure. Secret common." },
  "Electrical Engineer III": { what: "Leads electrical design of a subsystem and owns the qualification argument.", quals: "BS/MS + 8+ yrs. Technical authority for the electrical baseline." },
  "Electronics Technician I": { what: "Assembles, tests and troubleshoots electronic assemblies to documented procedures.", quals: "HS/associate + IPC-A-610. 0–3 yrs. Soldering certification." },
  "Electronics Technician II": { what: "Performs board-level fault isolation and repair, and supports engineering test.", quals: "Associate + 3–7 yrs. IPC-7711/7721 rework. Secret sometimes." },
  "Electronics Technician III": { what: "Leads test and troubleshooting on complex assemblies and mentors junior technicians.", quals: "Associate + 7+ yrs. Often the floor technical authority." },
  "Test Engineer": { what: "Writes and runs qualification and acceptance test procedures and owns the test report.", quals: "BS engineering + 3+ yrs. Environmental and functional test." },
  "Systems Analyst": { what: "Analyses how systems and data flow across a program and documents the as-is and to-be.", quals: "BS + 3+ yrs. Requirements and process modelling." },
  "Data Analyst": { what: "Builds the datasets and reporting a program office uses to manage cost, schedule and quality.", quals: "BS + 2+ yrs. SQL plus a BI tool. Often CDRL-facing." },
  "Network Engineer": { what: "Designs, configures and secures program networks and their boundary devices.", quals: "BS or equivalent + 3+ yrs. CCNA/CCNP. IAT II for DoD roles." },
  "Quality Engineer": { what: "Owns the quality plan, first-article inspection and corrective action for a product line.", quals: "BS + 3+ yrs. AS9100/ISO 9001 internal auditor. CQE valued." },
  "Aerospace Technician": { what: "Builds, inspects and reworks aerospace assemblies to drawing and process spec.", quals: "Associate or A&P + 2+ yrs. Composite or structures experience." },
  "Cybersecurity / CMMC Engineer": { what: "Implements and evidences NIST SP 800-171 controls and prepares the SPRS score and SSP.", quals: "BS + 5+ yrs. CISSP/CISM. CMMC CCP or CCA. Secret common." },
  "Program Manager I": { what: "Runs cost, schedule and scope for a program or a major subcontract.", quals: "BS + 5+ yrs. EVM familiarity. PMP common. Secret typical." },
  "Program Manager II": { what: "Owns P&L and customer relationship for a portfolio and negotiates scope changes.", quals: "BS/MBA + 10+ yrs. EVM, PMP. Secret or higher." },
  "Project Manager (Aerospace)": { what: "Runs a build-to-print or development project across engineering, supply chain and the floor.", quals: "BS + 5+ yrs in aerospace production. PMP valued." },
  "Contracts Manager": { what: "Owns the contract file, negotiates terms and manages mods, claims and closeout.", quals: "BS + 7+ yrs. NCMA CPCM/CFCM. FAR/DFARS fluency required." },
  "Contracts Administrator": { what: "Administers awards day to day — mods, data calls, reps and certs, closeout support.", quals: "BS + 2–6 yrs. CFCM valued. Working FAR knowledge." },
  "Cost Estimator": { what: "Builds the basis of estimate and the cost volume for proposals.", quals: "BS + 3+ yrs. Parametric and analogy methods. DCAA-aware." },
  "Price Analyst": { what: "Tests proposed pricing for reasonableness and prepares the price narrative.", quals: "BS + 3+ yrs. FAR 15.4 price analysis techniques." },
  "Budget Analyst": { what: "Plans and tracks program budgets and reconciles actuals to the baseline.", quals: "BS + 3+ yrs. Cost accounting. EVM exposure." },
  "Configuration Manager": { what: "Controls the product baseline — CDRLs, change boards, revision and release.", quals: "BS or equivalent + 5+ yrs. CMII valued. Secret common." },
  "Subcontract Administrator": { what: "Sources, awards and manages subcontracts including flowdowns and supplier performance.", quals: "BS + 3+ yrs. FAR flowdown fluency. NCMA valued." },
  "Sheet Metal Mechanic": { what: "Forms, fits and fastens sheet metal detail parts and assemblies to drawing.", quals: "HS + trade training + 2+ yrs. Blueprint reading." },
  "Aircraft Mechanic I": { what: "Performs scheduled maintenance and component removal and replacement under supervision.", quals: "A&P or military equivalent, 0–3 yrs." },
  "Aircraft Mechanic II": { what: "Performs unscheduled maintenance and fault isolation and signs off own work.", quals: "A&P + 4+ yrs. Type experience on the platform." },
  "Electronics Assembler": { what: "Assembles cable, harness and board-level product to IPC workmanship standards.", quals: "HS + IPC-A-610/620 certification." },
  "Quality Inspector": { what: "Inspects parts and assemblies against drawing and accepts or rejects against the plan.", quals: "HS/associate + 3+ yrs. GD&T, calipers, CMM familiarity." },
  "CMM Programmer / Machinist": { what: "Programs and runs coordinate measuring machines and reports dimensional results.", quals: "Associate or trade + 4+ yrs. PC-DMIS or Calypso. GD&T." },
  "CNC Machinist I": { what: "Sets up and runs CNC machines from an existing program and holds print tolerance.", quals: "Trade training + 1–3 yrs. Blueprint reading, basic metrology." },
  "CNC Machinist II": { what: "Programs, sets up and proves out CNC work on close-tolerance and exotic material.", quals: "Trade + 5+ yrs. Multi-axis. Mastercam or equivalent." },
  "Welder — Structural": { what: "Welds structural assemblies to a qualified procedure and passes visual and NDT.", quals: "AWS D1.1 qualification. 2+ yrs." },
  "Production Welder (Mil-Spec)": { what: "Welds to military specification under a qualified procedure with traceable filler and NDT.", quals: "AWS D17.1 or MIL-STD qualification. 3+ yrs." },
  "Tool & Die Maker": { what: "Builds and maintains tooling, fixtures and dies that hold production tolerance.", quals: "Apprenticeship + 5+ yrs. Precision grinding and fitting." },
  "Assembler — Precision": { what: "Assembles close-tolerance mechanical product to work instruction and torque spec.", quals: "HS + 2+ yrs. Torque and bonding process certification." },
  "NDT Technician": { what: "Performs non-destructive testing and interprets and reports indications.", quals: "NAS 410 / ASNT Level II in the applicable methods." },
  "Painter — Industrial": { what: "Prepares and applies protective and specification coatings to production hardware.", quals: "HS + 2+ yrs. Coating spec and respirator qualification." },
  "Supply Chain Analyst": { what: "Plans material, manages lead time and reports supply risk against the build schedule.", quals: "BS + 3+ yrs. APICS CPIM valued. ERP fluency." },
  "Purchasing Agent": { what: "Sources and buys material and services against approved requisitions.", quals: "BS or equivalent + 2+ yrs. Purchasing system knowledge." },
  "Inventory Control Specialist": { what: "Owns stock accuracy, cycle counting and material movement records.", quals: "HS/associate + 2+ yrs. ERP transactions, bonded stores." },
  "Warehouse Specialist": { what: "Receives, stores, kits and ships material against work orders.", quals: "HS + 1+ yrs. Forklift certification. Hazmat awareness." },
  "Shipping/Receiving Clerk": { what: "Processes inbound and outbound shipments and their documentation.", quals: "HS + 1+ yrs. Export documentation awareness." },
  "Logistician II": { what: "Plans provisioning, spares and sustainment data for a fielded system.", quals: "BS + 3+ yrs. LSA/LORA familiarity. Secret common." },
  "Security Specialist": { what: "Administers physical and personnel security and supports inspections.", quals: "BS or equivalent + 3+ yrs. NISPOM working knowledge." },
  "ISSO (InfoSec System Officer)": { what: "Maintains the security posture and ATO evidence for an accredited system.", quals: "BS + 5+ yrs. IAT/IAM II. RMF and eMASS. Secret or higher." },
  "FSO (Facility Security Officer)": { what: "Owns the facility clearance, NISPOM compliance and DCSA relationship.", quals: "BS or equivalent + 5+ yrs. FSO curriculum. Secret or higher." },
};
