// Brain card 81 Step 2 ($0) — temporal-conflict show-stopper over STORED gold sources. NO paid run.
//   npx tsx scripts/audit-ai/test-temporal-conflict.ts
import { readFileSync } from "node:fs";
import { highSignalSweep } from "../../src/lib/audit-grounding-sweep";
import { applyCautionFloor, applyTemporalConflict, deriveVerdict, parseDays } from "../../src/lib/audit-decide";
import type { TypedFinding, VerdictInputs } from "../../src/lib/audit-findings";

let fail = 0;
const ok = (c: boolean, m: string) => { console.log(`  [${c ? "PASS" : "FAIL"}] ${m}`); if (!c) fail++; };
const GOLD = "scripts/audit-ai/gold-sets";
const FROZEN = "tests/fixtures/frozen";
const src = (f: string) => readFileSync(`${GOLD}/${f}`, "utf8");
// Brain card 90: read FROZEN fixtures, never live ceo/proofs/ (those are regenerated by paid runs).
const frozen = (file: string) => (JSON.parse(readFileSync(`${FROZEN}/${file}`, "utf8")).findings as TypedFinding[]).map((f) => ({ ...f, grounded: true }));
// decide over a frozen fixture's COMPLETE finding set: apply temporal-conflict + caution-floor, then derive.
const decideFx = (findings: TypedFinding[]) => {
  let f = applyTemporalConflict(findings, { enabled: true });
  f = applyCautionFloor(f, { enabled: true });
  const inp: VerdictInputs = { findings: f, bidderProfile: null, coverageComplete: true, verifierSound: true, conflict: false, manifestComplete: true };
  return deriveVerdict(inp).verdict;
};

// ── parseDays unit ──
console.log("[parseDays]");
ok(parseDays("SIXTY (60) calendar days") === 60, `"SIXTY (60) calendar days" → ${parseDays("SIXTY (60) calendar days")}`);
ok(parseDays("NOT LATER THAN THIRTY (30) calendar days After Receipt of Order") === 30, `"THIRTY (30)..." → ${parseDays("NOT LATER THAN THIRTY (30) calendar days After Receipt of Order")}`);
ok(parseDays("within 30 days, or 90 days max") === 30, "smallest binding minimum picked (30 from 30/90)");
ok(parseDays("no day count here") === null, "no duration → null");

// ── B. NO_BID precondition × window — STATED invariants (Brain card 90), over FROZEN fixtures ──
console.log("\n[#6 FA860126Q00260001 — frozen fixtures]");
const fxComplete = frozen("fa8601-complete.json");
const fxNoPre = frozen("fa8601-no-precondition.json");
const fxNoWin = frozen("fa8601-no-window.json");
ok(decideFx(fxComplete) === "NO_BID", `complete (non-waivable precondition + impossible window) → ${decideFx(fxComplete)} (stated NO_BID)`);
ok(decideFx(fxNoPre) !== "NO_BID", `no-precondition (FAT precondition removed, window kept) → ${decideFx(fxNoPre)} (stated ≠NO_BID)`);
ok(decideFx(fxNoWin) !== "NO_BID", `no-window (precondition kept, window removed) → ${decideFx(fxNoWin)} (stated ≠NO_BID)`);

// ── #4 — regression: temporal-conflict must NOT affect it (no FAT precondition) → stays CAUTION ──
const fx4 = frozen("aocssb-with-qual.json");
console.log("\n[#4 AOCSSB26R0023 — frozen with-qual regression]");
ok(decideFx(fx4) === "BID_WITH_CAUTION", `temporal + floor → ${decideFx(fx4)} (unaffected by Step 2; stays CAUTION)`);

// ── #2 — regression: stays BID ──
const fx2 = frozen("1240lp-bid.json");
console.log("\n[#2 1240LP26Q0067 — frozen regression]");
ok(decideFx(fx2) === "BID", `temporal + floor → ${decideFx(fx2)} (stays BID)`);

// ── safety: non-waivable + duration-math guards ──
console.log("\n[safety guards]");
const mkFat = (excerpt: string): TypedFinding => ({ requirement: "FAT", citation: "§F", excerpt, kind: "technical_spec", controllability: "bidder_controls", grounded: true, lens: "deterministic_sweep", sweepArchetype: "fat_precondition" });
const mkDel = (excerpt: string): TypedFinding => ({ requirement: "delivery", citation: "§F", excerpt, kind: "technical_spec", controllability: "bidder_controls", grounded: true, lens: "deterministic_sweep", sweepArchetype: "delivery_window" });
const fires = (fat: string, del: string) => applyTemporalConflict([mkFat(fat), mkDel(del)], { enabled: true }).some((f) => f.controllability === "no_one_can_move");
ok(fires("NON-WAIVABLE first article testing SIXTY (60) calendar days before delivery", "deliver within THIRTY (30) calendar days ARO"), "non-waivable 60 > 30 → fires");
ok(!fires("first article testing of SIXTY (60) calendar days; the CO may waive at its discretion", "deliver within THIRTY (30) days ARO"), "WAIVABLE 60 vs 30 → does NOT fire (CO can waive → not universal)");
ok(!fires("NON-WAIVABLE first article testing of TWENTY (20) calendar days", "deliver within THIRTY (30) days ARO"), "non-waivable 20 ≤ 30 → does NOT fire (fits in window)");

// ── ANCHOR (Brain card 90): decide(complete frozen fixture) == the registry-resolved FROZEN GOLD-KEY verdict (#6) ──
const reg = JSON.parse(readFileSync("scripts/audit-ai/gold-sets/gold-set-registry.json", "utf8"));
const goldVerdict = (sol: string): string =>
  JSON.parse(readFileSync(`scripts/audit-ai/gold-sets/${reg.keys[sol].file}`, "utf8")).expectedVerdict.verdict;
console.log("\n[ANCHOR — fixture decide() == gold-key verdict]");
ok(decideFx(fxComplete) === goldVerdict("FA860126Q00260001"), `#6 decideFx(complete) = ${decideFx(fxComplete)} == gold-key ${goldVerdict("FA860126Q00260001")}`);

console.log("");
if (fail) { console.error(`✗ ${fail} check(s) FAILED`); process.exit(1); }
console.log("✓ STEP 2 GREEN — temporal-conflict emits no_one_can_move ⇒ NO_BID flips (sweep+temporal); #4 stays CAUTION, #2 stays BID; non-waivable + duration-math guards hold. $0.");
