/**
 * cross-system-writer.ts
 *
 * Stage 5: Cross-system writes for Email-AI verbs.
 *
 * Handles 3 verbs from email_ai_actions:
 *   - notion_update      → create page in Notion "Email-AI Action Inbox" DB
 *   - digest_p0_block    → append new P0 to digest-data.json p0[] array
 *   - digest_p0_unblock  → match-and-close existing open P0, move to completionsLog
 *
 * Every write logs to email_ai_writes for idempotency + rollback.
 * Forward-only by default: only processes actions with extracted_at > stage_5_ship_ts.
 *
 * Idempotency: UNIQUE INDEX on (action_id, verb) WHERE status='success'.
 * If a successful write exists, this skips the action.
 */
import { readFileSync, writeFileSync, copyFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import type { SupabaseClient } from "@supabase/supabase-js";

// Stable identifiers from the Notion DB created 2026-05-16
export const NOTION_EMAIL_AI_DB_ID = "ab3eda926047480faecdb82cd905bb6b";
export const NOTION_EMAIL_AI_DATA_SOURCE_ID = "8f94d2c0-5d58-4ae7-8c7b-a4cff2b28cf7";

// Hard cutover: forward-only writes from this ship time
// (action.extracted_at must be > this to be eligible)
export const STAGE_5_SHIP_TS = "2026-05-16T17:00:00Z";

const DIGEST_PATH = join(homedir(), "faraudit-app", "ceo", "digest-data.json");
const DIGEST_BACKUP_DIR = join(homedir(), "faraudit-app", "ceo", "backups");

export interface WriterResult {
  action_id: string;
  thread_id: string;
  verb: string;
  target_system: "notion" | "digest";
  target_ref: string;
  status: "success" | "failed" | "skipped";
  error?: string;
}

function gmailThreadUrl(threadId: string): string {
  return `https://mail.google.com/mail/u/0/#inbox/${threadId}`;
}

function backupDigest(): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = join(DIGEST_BACKUP_DIR, `digest-data-${ts}-stage5.json`);
  copyFileSync(DIGEST_PATH, backupPath);
  return backupPath;
}

// ─────────────────────────────────────────────────────────────
// Verb handler: notion_update
// ─────────────────────────────────────────────────────────────
async function handleNotionUpdate(
  action: any,
  classification: any
): Promise<{ target_ref: string; payload: any }> {
  const notionKey = process.env.NOTION_API_KEY;
  if (!notionKey) throw new Error("NOTION_API_KEY missing from env");

  const subject = classification?.subject ?? "(no subject)";
  const title = subject.slice(0, 200);
  const source = gmailThreadUrl(action.thread_id);

  const body = {
    parent: { type: "database_id", database_id: NOTION_EMAIL_AI_DB_ID },
    properties: {
      "Title": { title: [{ text: { content: title } }] },
      "Status": { select: { name: "Open" } },
      "Source": { url: source },
      "Verb": { select: { name: action.verb } },
      "Confidence": { number: action.confidence },
      "Action Reason": { rich_text: [{ text: { content: (action.reason ?? "").slice(0, 1900) } }] },
      "Thread ID": { rich_text: [{ text: { content: action.thread_id } }] },
      "Action ID": { rich_text: [{ text: { content: action.id } }] },
    },
  };

  const res = await fetch("https://api.notion.com/v1/pages", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${notionKey}`,
      "Content-Type": "application/json",
      "Notion-Version": "2022-06-28",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Notion API ${res.status}: ${errText.slice(0, 300)}`);
  }

  const pageData: any = await res.json();
  return { target_ref: pageData.id, payload: body };
}

// ─────────────────────────────────────────────────────────────
// Verb handler: digest_p0_block
// ─────────────────────────────────────────────────────────────
async function handleDigestP0Block(
  action: any,
  classification: any
): Promise<{ target_ref: string; payload: any }> {
  backupDigest();
  const digest = JSON.parse(readFileSync(DIGEST_PATH, "utf-8"));
  digest.p0 = digest.p0 ?? [];

  const existingIds = digest.p0.map((p: any) => p.id ?? "");
  const logIds = (digest.completionsLog ?? []).map((p: any) => p.id ?? "");
  const all = [...existingIds, ...logIds];
  const maxNum = all
    .map((id) => /^P0-(\d+)$/.exec(id))
    .filter(Boolean)
    .map((m: any) => parseInt(m[1], 10))
    .reduce((a, b) => Math.max(a, b), 0);
  const newId = `P0-${maxNum + 1}`;

  const subject = classification?.subject ?? "(no subject)";
  const newP0 = {
    id: newId,
    status: "open",
    title: `[Email-AI] ${subject.slice(0, 140)}`,
    detail: `Source: ${gmailThreadUrl(action.thread_id)}\nExtractor reason: ${action.reason ?? "(none)"}\nConfidence: ${action.confidence}\nAuto-generated by Email-AI Stage 5 from thread ${action.thread_id}.`,
    source: "email_ai",
    thread_id: action.thread_id,
    action_id: action.id,
    createdAt: new Date().toISOString().replace(/\.\d+/, ""),
  };

  digest.p0.push(newP0);
  digest.meta = digest.meta ?? {};
  digest.meta.last_updated = new Date().toISOString().replace(/\.\d+/, "");
  digest.kpi_counters = digest.kpi_counters ?? {};
  digest.kpi_counters.p0_open = digest.p0.filter((p: any) => p.status !== "closed").length;

  writeFileSync(DIGEST_PATH, JSON.stringify(digest, null, 2));
  return { target_ref: newId, payload: newP0 };
}

// ─────────────────────────────────────────────────────────────
// Verb handler: digest_p0_unblock
// ─────────────────────────────────────────────────────────────
async function handleDigestP0Unblock(
  action: any,
  _classification: any
): Promise<{ target_ref: string; payload: any }> {
  backupDigest();
  const digest = JSON.parse(readFileSync(DIGEST_PATH, "utf-8"));
  digest.p0 = digest.p0 ?? [];
  digest.completionsLog = digest.completionsLog ?? [];

  let matchedIndex = -1;
  for (let i = 0; i < digest.p0.length; i++) {
    const p = digest.p0[i];
    if (p.thread_id === action.thread_id || p.action_id === action.id) {
      matchedIndex = i;
      break;
    }
  }

  if (matchedIndex < 0) {
    throw new Error(`no matching open P0 with thread_id=${action.thread_id}`);
  }

  const closedP0 = digest.p0[matchedIndex];
  closedP0.status = "closed";
  const completion = {
    id: closedP0.id,
    title: closedP0.title,
    completedAt: new Date().toISOString().replace(/\.\d+/, ""),
    category: closedP0.category ?? "email_ai",
    evidence: `Auto-closed by Email-AI Stage 5 via thread ${action.thread_id}. Original detail: ${(closedP0.detail ?? "").slice(0, 300)}. Unblock signal: ${action.reason ?? "(none)"}.`,
    source: "email_ai_unblock",
  };
  digest.completionsLog.push(completion);
  digest.p0.splice(matchedIndex, 1);

  digest.meta = digest.meta ?? {};
  digest.meta.last_updated = new Date().toISOString().replace(/\.\d+/, "");
  digest.kpi_counters = digest.kpi_counters ?? {};
  digest.kpi_counters.p0_open = digest.p0.filter((p: any) => p.status !== "closed").length;
  digest.kpi_counters.completions_total = digest.completionsLog.length;

  writeFileSync(DIGEST_PATH, JSON.stringify(digest, null, 2));
  return { target_ref: closedP0.id, payload: completion };
}

// ─────────────────────────────────────────────────────────────
// Main dispatcher
// ─────────────────────────────────────────────────────────────
export async function processAction(
  sb: SupabaseClient,
  action: any,
  classification: any,
  tickId: string
): Promise<WriterResult> {
  const { data: existing } = await sb
    .from("email_ai_writes")
    .select("id, status")
    .eq("action_id", action.id)
    .eq("verb", action.verb)
    .eq("status", "success")
    .limit(1);
  if (existing && existing.length > 0) {
    return {
      action_id: action.id,
      thread_id: action.thread_id,
      verb: action.verb,
      target_system: action.verb === "notion_update" ? "notion" : "digest",
      target_ref: "(already-written)",
      status: "skipped",
    };
  }

  const target_system: "notion" | "digest" = action.verb === "notion_update" ? "notion" : "digest";

  const { data: pending, error: pendErr } = await sb
    .from("email_ai_writes")
    .insert({
      action_id: action.id,
      thread_id: action.thread_id,
      tick_id: tickId,
      verb: action.verb,
      target_system,
      target_ref: "(pending)",
      payload: {},
      status: "pending",
    })
    .select("id")
    .single();
  if (pendErr) throw new Error(`insert pending failed: ${pendErr.message}`);

  try {
    let result: { target_ref: string; payload: any };
    if (action.verb === "notion_update") {
      result = await handleNotionUpdate(action, classification);
    } else if (action.verb === "digest_p0_block") {
      result = await handleDigestP0Block(action, classification);
    } else if (action.verb === "digest_p0_unblock") {
      result = await handleDigestP0Unblock(action, classification);
    } else {
      throw new Error(`unsupported verb: ${action.verb}`);
    }

    await sb
      .from("email_ai_writes")
      .update({
        target_ref: result.target_ref,
        payload: result.payload,
        status: "success",
        applied_at: new Date().toISOString(),
      })
      .eq("id", pending.id);

    return {
      action_id: action.id,
      thread_id: action.thread_id,
      verb: action.verb,
      target_system,
      target_ref: result.target_ref,
      status: "success",
    };
  } catch (e: any) {
    const errMsg = e?.message ?? String(e);
    await sb
      .from("email_ai_writes")
      .update({
        status: "failed",
        error_message: errMsg.slice(0, 1000),
      })
      .eq("id", pending.id);

    return {
      action_id: action.id,
      thread_id: action.thread_id,
      verb: action.verb,
      target_system,
      target_ref: "(failed)",
      status: "failed",
      error: errMsg,
    };
  }
}
